server:
  port: 31400
spring:
  application:
    name: xc-service-manager-media
  data:
    mongodb:
      uri: mongodb://192.168.73.128:27017
      database: xc_media
  rabbitmq:
    host: 192.168.73.128
    port: 5672
    username: guest
    password: guest
xc-service-manager-media:
  upload-location: D:/test/video/
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video


eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

ribbon:
  MaxAutoRetries: 2 #最大重试次数
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false # 对所有操作进行重试, 如果是get则可以, 如果是post put 则没有次数
  ConnectionTimeout: 5000 # 请求连接的时间
  ReadTimeout: 6000 # 请求处理的时间

