server:
  port: 40600
spring:
  application:
    name: xc-service-learning
  datasource:
    url: jdbc:mysql://localhost:3306/xc_learning
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  rabbitmq:
    host: 192.168.73.128
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

mybatis:
  mapper-locations: classpath:/mapper/*.xml

feign:
  client:
    default:
#这里时间一定要调长，否则feign客户端会报ReadTimeOut  服务端报Error parsing HTTP request header
      connectTimeout: 60000
      readTimeout: 60000

ribbon:
  MaxAutoRetries: 2 #最大重试次数
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false # 对所有操作进行重试, 如果是get则可以, 如果是post put 则没有次数
  ConnectionTimeout: 5000 # 请求连接的时间
  ReadTimeout: 6000 # 请求处理的时间


course-publish:
  siteId: 5e8aad058088a242dac66573
  templateId: 5ad9a24d68db5239b8fef199
  previewUrl: http://www.xuecheng.com/cms/preview/
  pageWebPath: /course/detail/
  pagePhysicalPath: /course/detail/
  dataUrl: http://localhost:31200/course/courseviews/
