server:
  port: 22100
spring:
  application:
    name: xc-service-filesystem
  data:
    mongodb:
      uri: mongodb://192.168.73.128:27017
      database: xc_cms
  # SpringMvc上传文件
  servlet:
    multipart:
      # 默认支撑上传文件
      enabled: true
      # 支持文件写入磁盘
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 1MB
      # 最大支持请求大小
      max-request-size: 30MB

xc:
  fastdfs:
    # http连接时间
    connect_timeout_in_seconds: 5
    # tracker与storage网络通信超时时间
    network_timeout_in_seconds: 30
    #字符编码
    charset: UTF-8
    # tracker服务器地址, 多个地址中间用英文逗号分隔
    tracker_servers: 192.168.73.128:22122
