server:
  port: 40400
  servlet:
    context-path: /auth
spring:
  application:
    name: xc-service-ucenter-auth
  data:
    mongodb:
      uri: mongodb://47.114.111.3:27017
      database: xc_cms
  redis:
    host: 47.114.111.3
    port: 6379
    timeout: 5000 # 连接超时
    jedis:
      pool:
        max-active: 3
        max-idle: 3
        max-wait: -1  # 连接池最大等行时间, -1表示没有限制
        min-idle: 1
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_user
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      initial-size: 5 # 初始建立连接数量
      min-idle: 5  # 最小连接数量
      max-active: 20 # 最大连接数据
      max-wait: 10000  # 最大连接等待时间
      test-on-borrow: true # 申请连接时检测连接是否有效
      test-on-return: false  # 归还连接时检测连接是否有效
      time-between-eviction-runs-millis: 60000  # 配置间隔检测连接是否有效的时间
      min-evictable-idle-time-millis: 300000 # 连接在连接池的最小生存时间
auth:
  tokenValiditySeconds: 1200 # token存储到redis的过期时间
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomin: xuecheng.com
  cookieMaxAge: -1
#
encrypt:
  key-store:
    location: classpath:/xc.keystore
    secret: xuechengkeystore
    alias: xckey
    password: xuecheng


eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

ribbon:
  MaxAutoRetries: 2 #最大重试次数
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false # 对所有操作进行重试, 如果是get则可以, 如果是post put 则没有次数
  ConnectionTimeout: 5000 # 请求连接的时间
  ReadTimeout: 6000 # 请求处理的时间
